import { theme } from "antd";

export const themeOptions = {
  orokin: {
    label: "Orokin",
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: "#CA8A04",
      colorSuccess: "#22C55E",
      colorWarning: "#F59E0B",
      colorError: "#EF4444",
      colorBgBase: "#0B0B10",
      colorBgContainer: "#1B1B30",
      colorBgElevated: "#27273B",
      colorText: "#F8FAFC",
      colorTextSecondary: "#94A3B8",
      colorBorder: "#1E293B",
      colorScrollbar: "#CA8A04",
      borderRadius: 10,
    },
  },
  drifter: {
    label: "Drifter",
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: "#D97706",
      colorSuccess: "#059669",
      colorWarning: "#FBBF24",
      colorError: "#DC2626",
      colorBgBase: "#0F172A",
      colorBgContainer: "#192134",
      colorBgElevated: "#1F2B3F",
      colorText: "#FFFFFF",
      colorTextSecondary: "#94A3B8",
      colorBorder: "rgba(255,255,255,0.08)",
      colorScrollbar: "#D97706",
      borderRadius: 8,
    },
  },
  lotus: {
    label: "Lotus",
    algorithm: theme.defaultAlgorithm,
    token: {
      colorPrimary: "#3B82F6",
      colorSuccess: "#22C55E",
      colorWarning: "#F59E0B",
      colorError: "#EF4444",
      colorBgBase: "#F1F5F9",
      colorBgContainer: "#FFFFFF",
      colorBgElevated: "#F8FAFC",
      colorText: "#0F172A",
      colorTextSecondary: "#64748B",
      colorBorder: "#E2E8F0",
      colorScrollbar: "#94A3B8",
      borderRadius: 10,
    },
  },
};

export const colorFields = [
  ["colorPrimary", "customPrimary"],
  ["colorBgBase", "customBgBase"],
  ["colorBgContainer", "customBgContainer"],
  ["colorText", "customText"],
  ["colorTextSecondary", "customTextSecondary"],
  ["colorBorder", "customBorder"],
  ["colorScrollbar", "customScrollbar"],
  ["colorSuccess", "customSuccess"],
  ["colorWarning", "customWarning"],
  ["colorError", "customError"],
];
