import { theme } from "antd";

export const themeOptions = {
  orokin: {
    label: "Orokin",
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: "#CA8A04",
      colorSuccess: "#22C55E",
      colorWarning: "#F59E0B",
      colorError: "#EF4444",
      colorBgBase: "#0D0D14",
      colorBgContainer: "#141420",
      colorBgElevated: "#1A1A28",
      colorText: "#F8FAFC",
      colorTextSecondary: "#94A3B8",
      colorBorder: "#1E293B",
      colorScrollbar: "#CA8A04",
      borderRadius: 10,
    },
  },
  drifter: {
    label: "Drifter",
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: "#10B981",
      colorSuccess: "#34D399",
      colorWarning: "#FBBF24",
      colorError: "#F87171",
      colorBgBase: "#0E1218",
      colorBgContainer: "#14191F",
      colorBgElevated: "#1A2028",
      colorText: "#E2E8F0",
      colorTextSecondary: "#7C8CA2",
      colorBorder: "rgba(16,185,129,0.12)",
      colorScrollbar: "#10B981",
      borderRadius: 6,
    },
  },
  lotus: {
    label: "Lotus",
    algorithm: theme.defaultAlgorithm,
    token: {
      colorPrimary: "#3B82F6",
      colorSuccess: "#22C55E",
      colorWarning: "#F59E0B",
      colorError: "#EF4444",
      colorBgBase: "#F1F5F9",
      colorBgContainer: "#FFFFFF",
      colorBgElevated: "#F8FAFC",
      colorText: "#0F172A",
      colorTextSecondary: "#64748B",
      colorBorder: "#E2E8F0",
      colorScrollbar: "#94A3B8",
      borderRadius: 10,
    },
  },
};

export const colorFields = [
  ["colorPrimary", "customPrimary"],
  ["colorBgBase", "customBgBase"],
  ["colorBgContainer", "customBgContainer"],
  ["colorText", "customText"],
  ["colorTextSecondary", "customTextSecondary"],
  ["colorBorder", "customBorder"],
  ["colorScrollbar", "customScrollbar"],
  ["colorSuccess", "customSuccess"],
  ["colorWarning", "customWarning"],
  ["colorError", "customError"],
];
